### PR TITLE
fix: allow non-English characters in filename

### LINKED ISSUE #2: Chinese and Japanese characters are omitted
Hi! This is a very useful plugin. However, I am finding that Chinese and Japanese characters are omitted from the generated file name.
For example, foo中文テストbar will be named as foobar.

### PR DESCRIPTION
**Pull request by john-walks-slow**
Instead of a list of allowed chars, I keep a list of illegal chars now. ([reference](https://stackoverflow.com/a/35352640/9519602))

`#^[]` are allowed previously, but is now avoided, because they are illegal in obsidian. 
screenshot

All consecutive white space characters are replaced with a single space.

fixes #2

### CODE REVIEW

File: src/main.ts [hunk 1]
```diff
@@ -118,20 +118,21 @@ export default class AutoFilename extends Plugin {
 					newFileName += "..."; // Adds "..." at the end to indicate there might be more text.
 					break;
 				}
-
-				char = " "; // Treat new lines as spaces.
```
Comment (rcsaquino) [inline src/main.ts:122]: I'm curious as to why you removed this line? This is supposed to make `The quick brown fox\njumps over` would make the filename `The quick brown fox jumps over` instead of `The quick brown foxjumps over`.

File: src/main.ts [hunk 2]
```diff
@@ -118,20 +118,21 @@ export default class AutoFilename extends Plugin {
...
 			}
 
-			if (allowedChars.includes(char)) newFileName += char;
+			// Avoid illegal characters in filenames
+			if (!(illegalChars.includes(char))) newFileName += char;
 		}
 
-		newFileName = newFileName.trim(); // Trim white space
+		newFileName = newFileName.trim() // Trim white spaces
+			.replace(/\s+/g, " "); // Replace consecutive whitespace characters with a space
```
Comment (rcsaquino) [inline src/main.ts:130]: At the end of long filenames, we append a [triple dot](https://github.com/rcsaquino/obsidian-auto-filename/blob/a45564ab6ceab88c304bd220290fdf4351abc947/src/main.ts#L118) (...) to signify there might be more text that are cutoff. This is purely for aesthetic purposes so long texts would have a filename of `This is a very long filename...` instead `This is a very long filename ...` (notice the space before "..."). I do not get the purpose of the added replace regex function. Can you explain this more?

**Review by rcsaquino — CHANGES_REQUESTED** [review]
